[preface]
== Securing the Software Supply Chain

This work copyright © 2025 by Michael Lieberman and Brandon Lum.
It is published under the Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA) license.footnote:[https://creativecommons.org/licenses/by-sa/4.0/]
To report errors or view errata, visit the GitHub repo.footnote:[{url-repo}]

=== Version History

* Version 1.0rc1 — 2025-03-19 — Initial publication

=== About the Authors

==== Michael Lieberman

Michael Lieberman is co-founder and CTO of Kusari where he helps build transparency and security in the software supply chain.
Michael is an active member of the open source community, co-creating the GUAC and FRSCA projects and co-leading the CNCF’s Secure Software Factory Reference Architecture whitepaper.
He is an elected member of the OpenSSF Governing Board and Technical Advisory Council along with CNCF TAG Security Lead and an SLSA steering committee member.

==== Brandon Lum

Brandon Lum is a seasoned technologist with a passion for designing and implementing security systems.
His experience spans cutting-edge research at IBM Research, where he focused on zero trust workload identity, kernel attack surface reduction, and image encryption/signing, to security hardening and offensive security at KPMG and as part of the PPP CTF team.
At Google, he is a lead of the Software Supply Chain Integrity (SSCI) observability initiative, where he spearheads the aggregation and synthesis of Google’s extensive software supply chain metadata, including SBOM, SLSA, and VEX, at scale.
His work delivers critical risk insights to Alphabet’s board and provides actionable intelligence to Google’s diverse business units.

Beyond Google, Brandon is an influential figure in the open-source and security standards communities.
He serves as Co-chair Emeritus of the CNCF Security TAG and maintains key security projects like SPDX, OpenVEX, GUAC, and SPIFFE/SPIRE.
He has authored numerous security standards and whitepapers, including SPDX 3.0, CISA publications on SBOM and VEX, and NIST Industry Reports on zero trust, as well as the book _Solving the Bottom Turtlefootnote:[https://spiffe.io/pdf/Solving-the-bottom-turtle-SPIFFE-SPIRE-Book.pdf]_ on zero trust architecture.

=== Credits

* **Editor:** Ben Cotton
* **Cover design:** Deccafootnote:[https://www.decdesign.com/]
* **Rendering:** Asciidoctorfootnote:[https://asciidoctor.org]