[preface]
== Securing the Software Supply Chain

This work copyright © 2025 by Michael Lieberman and Brandon Lum.
It is published under the Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA) license.footnote:[https://creativecommons.org/licenses/by-sa/4.0/]
To report errors or view errata, visit the GitHub repo.footnote:[{url-repo}]

=== Version History

* Version 1.0rc1 — 2025-03-19 — Initial publication

=== About the Authors

==== Michael Lieberman

Michael Lieberman is co-founder and CTO of Kusari where he helps build transparency and security in the software supply chain.
Michael is an active member of the open source community, co-creating the GUAC and FRSCA projects and co-leading the CNCF’s Secure Software Factory Reference Architecture whitepaper.
He is an elected member of the OpenSSF Governing Board and Technical Advisory Council along with CNCF TAG Security Lead and an SLSA steering committee member.

==== Brandon Lum

Brandon loves designing and implementing computer systems (with a focus on Security, Operating Systems, and Distributed/Parallel Systems).
Brandon is a co-chair of the CNCF Security TAG.
As a part of Google's Open Source Security Team, he works on improving the security of the open source ecosystem.
Previously at IBM Research, Brandon worked on various security areas such as:
container content protection via encryption and image signing, identity, and kernel attack surface reduction.

=== Credits

* **Editor:** Ben Cotton
* **Cover design:** Deccafootnote:[https://www.decdesign.com/]
* **Rendering:** Asciidoctorfootnote:[https://asciidoctor.org]